version: '3.8'

services:
  causal-econ:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: causal-econ
    ports:
      - "8888:8888"
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root

