version: '3.8'

services:
  anomaly_project:
    build: .
    container_name: anomaly_detection
    ports:
      - "8888:8888"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
